# Generated by Django 5.0.6 on 2024-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetculture',
            name='culture_type',
            field=models.CharField(choices=[('SKATEBOARD', 'Скейтбординг'), ('PARKOUR', 'Паркур'), ('WORKOUT', 'Воркаут'), ('FREERUN', 'Фриран'), ('HIP-HOP DANCE', 'Хип-хоп танцы'), ('TRICKING', 'Трикинг'), ('RAP', 'Рэп'), ('BREAKING', 'Брейк-данс'), ('BMX', 'БМХ'), ('SKATEBOARDING', 'Скейтбординг'), ('SCOOT', 'Скутер')], default='SKATEBOARD', max_length=50, verbose_name='Тип культуры'),
        ),
        migrations.DeleteModel(
            name='StreetCultureType',
        ),
    ]
