# Generated by Django 5.0.6 on 2024-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ogrn',
            field=models.CharField(max_length=13, verbose_name='ОГРН организации'),
        ),
    ]
