# Generated by Django 5.0.6 on 2024-05-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='federalteam',
            options={'verbose_name': 'Федеральная команда', 'verbose_name_plural': 'Федеральные команды'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Медиа', 'verbose_name_plural': 'Медиа'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='partnertype',
            options={'verbose_name': 'Тип партнера', 'verbose_name_plural': 'Типы партнеров'},
        ),
        migrations.AlterModelOptions(
            name='regionalteam',
            options={'verbose_name': 'Региональная команда', 'verbose_name_plural': 'Региональные команды'},
        ),
    ]
