# Generated by Django 5.0.6 on 2024-05-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_region_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.gallery', verbose_name='Галерея'),
        ),
    ]
