# Generated by Django 4.2.7 on 2024-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_aboutus_options_alter_federalteam_options_and_more'),
        ('aboutus', '0003_alter_media_gallery'),
    ]

    operations = [
    ]
