# Generated by Django 4.2.7 on 2024-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_merge_20240515_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер проекта', 'verbose_name_plural': 'Партнеры проекта'},
        ),
    ]
