import BackgroundImg from '@/public/images/disciplines/disciplines_bg.jpg'
import Image from 'next/image'
import { DisciplinesHead } from './_components/_head'

export const metadata = {
  title: 'Streets of Russia',
  description: 'Generated by Next.js',
}

export default function DisciplinesLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div style={{ position: 'relative' }}>
        <Image fill style={{ zIndex: -1 }} src={BackgroundImg} alt="concrete" priority />
        <DisciplinesHead />
        {children}
      </div>
    </>
  )
}
