# Generated by Django 5.0.6 on 2024-05-16 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите реальный мобильный телефонв формате 89XXXXXXXXX', regex='^89\\d{9}$')], verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('promoter', 'Организатор'), ('admin', 'Администратор')], default='promoter', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_nick',
            field=models.CharField(max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Некорректный ник телеграм', regex='^@[\\w\\d_]{5,32}$')], verbose_name='Имя пользователя в телеграм'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='third_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Попытка регистрации пользователя под me-образным именем', regex='^[mM][eE]$')], verbose_name='Имя пользователя'),
        ),
    ]
