# Generated by Django 5.0.6 on 2024-05-22 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
        ('users', '0002_remove_customuser_surname_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите реальный мобильный телефон в формате 89XXXXXXXXX', regex='^89\\d{9}$')], verbose_name='Мобильный телефон'),
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='regions',
            field=models.ManyToManyField(through='users.UserRegion', to='aboutus.region'),
        ),
    ]
