# Generated by Django 5.0.6 on 2024-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_userregion_customuser_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('fed manager', 'Федеральный руководитель'), ('reg manager', 'Региональный руководитель'), ('participant', 'Участник')], default='participant', max_length=16, verbose_name='Роль'),
        ),
    ]
