# Generated by Django 5.0.6 on 2024-05-22 07:58

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_birthday], verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите реальный мобильный телефон в формате 89XXXXXXXXX', regex='^89\\d{9}$')], verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_nick',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Некорректный ник телеграм', regex='^@[\\w\\d_]{5,32}$')], verbose_name='Имя пользователя в телеграм'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='third_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
