# Generated by Django 5.0.6 on 2024-05-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_avatar_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregion',
            options={'verbose_name': 'пользователь-регион', 'verbose_name_plural': 'пользователи-регионы'},
        ),
    ]
