# Generated by Django 5.0.6 on 2024-05-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='qrcodes')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='events.event')),
            ],
        ),
    ]
