# Generated by Django 5.0.6 on 2024-05-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_coordinates_eventlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinates',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventlocation',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='discipline',
            field=models.CharField(choices=[('STREET-ART', 'STREET-ART'), ('PARKOUR', 'PARKOUR'), ('WORKOUT', 'WORKOUT'), ('БМХ', 'БМХ'), ('СКЕЙТБОРДИНГ', 'СКЕЙТБОРДИНГ'), ('ТРЮКОВОЙ САМОКАТ', 'ТРЮКОВОЙ САМОКАТ'), ('ФРИРАН', 'ФРИРАН'), ('ТРИКИНГ', 'ТРИКИНГ'), ('БРЕЙК-ДАНС', 'БРЕЙК-ДАНС'), ('ГРАФФИТИ', 'ГРАФФИТИ'), ('ДИДЖЕИНГ', 'ДИДЖЕИНГ'), ('РЕП', 'РЕП')], default=1, max_length=50, verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('competition', 'Соревнование'), ('training', 'Тренировка'), ('event', 'Мероприятие')], default=1, max_length=50, verbose_name='Тип события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(default=1, max_length=255, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='coordinates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.coordinates'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
