import Footer from '../components/Footer'
import Header from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'Streets of Russia',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div style={{ display: 'flex', flexDirection: 'column', maxWidth: '1440px', margin: '0 auto' }}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
