# Generated by Django 5.0.6 on 2024-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=1, upload_to='blogs/images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='relevance_date',
            field=models.DateField(default='2024-1-1', verbose_name='Крайняя дата актуальности новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('post', 'Пост'), ('news', 'Новость')], default='post', max_length=4, verbose_name='Тип поста'),
        ),
    ]
