# Generated by Django 5.0.6 on 2024-05-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postregion',
            options={'verbose_name': 'пост-регион', 'verbose_name_plural': 'посты-регионы'},
        ),
    ]
