# Generated by Django 5.0.6 on 2024-05-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
        ('blog', '0002_blogpost_image_blogpost_relevance_date_blogpost_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.region')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='region',
            field=models.ManyToManyField(through='blog.PostRegion', to='aboutus.region'),
        ),
    ]
