# Generated by Django 5.0.6 on 2024-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postregion_blogpost_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('post', 'Пост'), ('reg news', 'Региональная новость'), ('fed news', 'Федеральная новость')], default='post', max_length=16, verbose_name='Тип поста'),
        ),
    ]
