# Generated by Django 5.0.6 on 2024-05-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postregion',
            options={'verbose_name': 'Пост-регион', 'verbose_name_plural': 'Посты-регионы'},
        ),
    ]
